# Generated by Django 3.0.8 on 2020-07-09 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RESTapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disease',
            new_name='Pandemic',
        ),
    ]
