# Generated by Django 3.0.8 on 2020-07-09 06:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('RESTapp', '0002_auto_20200709_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pandemic',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
